spring.application.name=web
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/applogin?useTimezone=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:changeme}